apiVersion: v1
kind: ConfigMap
metadata:
  name: smallbank-configmap
data:
  SPRING_PROFILES_ACTIVE: prod
  SPRING_CONFIG_IMPORT: "configserver:http://configserver-service:8071/"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver:8070/eureka/"
  CONFIGSERVER_APPLICATION_NAME: configserver
  EUREKA_APPLICATION_NAME: eurekaserver
  ACCOUNTS_APPLICATION_NAME: accounts
  LOANS_APPLICATION_NAME: loans
  CARDS_APPLICATION_NAME: cards
  GATEWAY_APPLICATION_NAME: gatewayserver
  KC_BOOTSTRAP_ADMIN_USERNAME: admin
  KC_BOOTSTRAP_ADMIN_PASSWORD: admin
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:7080/realms/master/protocol/openid-connect/certs"
  ACCOUNTS_DATASOURCE_URL: "jdbc:h2:mem:accountsdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
  LOANS_DATASOURCE_URL: "jdbc:h2:mem:loansdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
  CARDS_DATASOURCE_URL: "jdbc:h2:mem:cardsdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
