CREATE TABLE IF NOT EXISTS `users` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(50) NOT NULL,
    `EMAIL` VARCHAR(70) NOT NULL,
    `HASHED_PASSWORD` VARCHAR(200) NOT NULL,
    `CREATED_AT` TIMESTAMP NULL,
    `UPDATED_AT` TIMESTAMP NULL,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_users_EMAIL` (`EMAIL`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `expense_category` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `CATEGORY_NAME` VARCHAR(50) NOT NULL,
    `CREATED_AT` TIMESTAMP NULL,
    `UPDATED_AT` TIMESTAMP NULL,
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `expense_list` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(50) NOT NULL,
    `AMOUNT` DOUBLE NOT NULL,
    `USER_ID` BIGINT NOT NULL,
    `CATEGORY_ID` BIGINT NOT NULL,
    `CREATED_AT` TIMESTAMP NULL,
    `UPDATED_AT` TIMESTAMP NULL,
    PRIMARY KEY (`ID`),
    CONSTRAINT `FK_expense_list_user`
        FOREIGN KEY (`USER_ID`)
        REFERENCES `users` (`ID`)
        ON DELETE CASCADE,
    CONSTRAINT `FK_expense_list_category`
        FOREIGN KEY (`CATEGORY_ID`)
        REFERENCES `expense_category` (`ID`)
) ENGINE=InnoDB;
