services:
  rabbit:
    image: "rabbitmq:3.13-management"
    
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: "rabbitmq-diagnostics check_port_connectivity"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "sumanydv/configserver:v1"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'exec 3<>/dev/tcp/127.0.0.1/8071 && printf \"GET /actuator/health HTTP/1.0\\r\\nHost: localhost\\r\\n\\r\\n\" >&3 && cat <&3 | grep -q \"\\\"status\\\":\\\"UP\\\"\"'"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "sumanydv/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "sumanydv/loans:v1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "sumanydv/cards:v1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  smallBank:
    driver: bridge
